apiVersion: v2
name: openshift-challenge
description: OpenShift challenge environment
type: application
version: 0.1.0
appVersion: "1.0.0"

maintainers:
  - name: Robert Bohne
    email: robert.bohne@redhat.com
